// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using kurs.Context;

#nullable disable

namespace kurs.Data.Migrations
{
    [DbContext(typeof(MagazinminContext))]
    [Migration("20240518154710_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("kurs.Models.Dostavka", b =>
                {
                    b.Property<int>("IdDostavka")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_dostavka");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("IdDostavka"));

                    b.Property<DateOnly?>("DataPolucheniya")
                        .HasColumnType("date")
                        .HasColumnName("data_polucheniya");

                    b.Property<DateOnly?>("OjdaemayaData")
                        .HasColumnType("date")
                        .HasColumnName("ojdaemaya_data");

                    b.Property<string>("StatusDostavki")
                        .HasMaxLength(20)
                        .HasColumnType("character(20)")
                        .HasColumnName("status_dostavki")
                        .IsFixedLength();

                    b.HasKey("IdDostavka")
                        .HasName("dostavka_pkey");

                    b.ToTable("dostavka", (string)null);
                });

            modelBuilder.Entity("kurs.Models.Pokupatel", b =>
                {
                    b.Property<int>("IdPokupatel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_pokupatel");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("IdPokupatel"));

                    b.Property<string>("PokupatelAdresDostavki")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character(50)")
                        .HasColumnName("pokupatel_adres_dostavki")
                        .IsFixedLength();

                    b.Property<string>("PokupatelFio")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character(40)")
                        .HasColumnName("pokupatel_fio")
                        .IsFixedLength();

                    b.Property<decimal>("PokupatelTelefon")
                        .HasPrecision(11)
                        .HasColumnType("numeric(11)")
                        .HasColumnName("pokupatel_telefon");

                    b.HasKey("IdPokupatel")
                        .HasName("pokupatel_pkey");

                    b.HasIndex(new[] { "PokupatelTelefon" }, "pokupatel_pokupatel_telefon_key")
                        .IsUnique();

                    b.ToTable("pokupatel", (string)null);
                });

            modelBuilder.Entity("kurs.Models.SborschikZakaza", b =>
                {
                    b.Property<int>("IdSborschikZakaza")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_sborschik_zakaza");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("IdSborschikZakaza"));

                    b.Property<string>("SborschikZakazaNames")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character(40)")
                        .HasColumnName("sborschik_zakaza_names")
                        .IsFixedLength();

                    b.Property<decimal>("SborschikZakazaTelefon")
                        .HasPrecision(11)
                        .HasColumnType("numeric(11)")
                        .HasColumnName("sborschik_zakaza_telefon");

                    b.HasKey("IdSborschikZakaza")
                        .HasName("sborschik_zakaza_pkey");

                    b.HasIndex(new[] { "SborschikZakazaTelefon" }, "sborschik_zakaza_sborschik_zakaza_telefon_key")
                        .IsUnique();

                    b.ToTable("sborschik_zakaza", (string)null);
                });

            modelBuilder.Entity("kurs.Models.Tovar", b =>
                {
                    b.Property<int>("IdTovar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_tovar");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("IdTovar"));

                    b.Property<decimal?>("Cena")
                        .HasPrecision(10)
                        .HasColumnType("numeric(10)")
                        .HasColumnName("cena");

                    b.Property<int?>("IdZakaz")
                        .HasColumnType("integer")
                        .HasColumnName("id_zakaz");

                    b.Property<int?>("Kolichestvo")
                        .HasColumnType("integer")
                        .HasColumnName("kolichestvo");

                    b.Property<string>("TovarNaimenovanie")
                        .HasMaxLength(100)
                        .HasColumnType("character(100)")
                        .HasColumnName("tovar_naimenovanie")
                        .IsFixedLength();

                    b.HasKey("IdTovar")
                        .HasName("tovar_pkey");

                    b.HasIndex("IdZakaz");

                    b.ToTable("tovar", (string)null);
                });

            modelBuilder.Entity("kurs.Models.Zakaz", b =>
                {
                    b.Property<int>("IdZakaz")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_zakaz");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("IdZakaz"));

                    b.Property<int>("IdDostavka")
                        .HasColumnType("integer")
                        .HasColumnName("id_dostavka");

                    b.Property<int>("IdPokupatel")
                        .HasColumnType("integer")
                        .HasColumnName("id_pokupatel");

                    b.Property<int>("IdSborschikZakaza")
                        .HasColumnType("integer")
                        .HasColumnName("id_sborschik_zakaza");

                    b.Property<int?>("TovarIdTovar")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ZakazData")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("zakaz_data");

                    b.Property<decimal>("ZakazSumma")
                        .HasPrecision(5)
                        .HasColumnType("numeric(5)")
                        .HasColumnName("zakaz_summa");

                    b.HasKey("IdZakaz")
                        .HasName("zakaz_pkey");

                    b.HasIndex("IdDostavka");

                    b.HasIndex("IdPokupatel");

                    b.HasIndex("IdSborschikZakaza");

                    b.HasIndex("TovarIdTovar");

                    b.ToTable("zakaz", (string)null);
                });

            modelBuilder.Entity("kurs.Models.Tovar", b =>
                {
                    b.HasOne("kurs.Models.Zakaz", "IdZakazNavigation")
                        .WithMany("Tovar")
                        .HasForeignKey("IdZakaz")
                        .HasConstraintName("zakaz_tovar");

                    b.Navigation("IdZakazNavigation");
                });

            modelBuilder.Entity("kurs.Models.Zakaz", b =>
                {
                    b.HasOne("kurs.Models.Dostavka", "IdDostavkaNavigation")
                        .WithMany("Zakaz")
                        .HasForeignKey("IdDostavka")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("zakaz_dostavka");

                    b.HasOne("kurs.Models.Pokupatel", "IdPokupatelNavigation")
                        .WithMany("Zakaz")
                        .HasForeignKey("IdPokupatel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("zakaz_id_pokupatel");

                    b.HasOne("kurs.Models.SborschikZakaza", "IdSborschikZakazaNavigation")
                        .WithMany("Zakaz")
                        .HasForeignKey("IdSborschikZakaza")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("zakaz_id_sborschik_zakaza");

                    b.HasOne("kurs.Models.Tovar", null)
                        .WithMany("Zakaz")
                        .HasForeignKey("TovarIdTovar");

                    b.Navigation("IdDostavkaNavigation");

                    b.Navigation("IdPokupatelNavigation");

                    b.Navigation("IdSborschikZakazaNavigation");
                });

            modelBuilder.Entity("kurs.Models.Dostavka", b =>
                {
                    b.Navigation("Zakaz");
                });

            modelBuilder.Entity("kurs.Models.Pokupatel", b =>
                {
                    b.Navigation("Zakaz");
                });

            modelBuilder.Entity("kurs.Models.SborschikZakaza", b =>
                {
                    b.Navigation("Zakaz");
                });

            modelBuilder.Entity("kurs.Models.Tovar", b =>
                {
                    b.Navigation("Zakaz");
                });

            modelBuilder.Entity("kurs.Models.Zakaz", b =>
                {
                    b.Navigation("Tovar");
                });
#pragma warning restore 612, 618
        }
    }
}
